### ISSUE TITLE
Unneeded computation in ssi()

### ISSUE THREAD

**Issue by jacob-long** [mbojan/isnar#7]
I appreciate you making this package available as I've been wanting to calculate some segregation indices outlined in your 2014 *Social Networks* article.

I spotted what I believe is an easily corrected performance bottleneck in the `ssi()` function. Using a relatively large, weighted network --- about 2500 nodes and 2000000 edges --- the function wasn't finishing even as I let it run about 24 hours. I realized what was taking so long. This line:

```r
l <- get.adjedgelist(gg, mode="out")
```

After spending some time trying to figure out if there was a faster way to generate this, I realized something else: `l` isn't used! It just gets overwritten a few lines later. I can see in 2673759 that you used to use the output from `get.adjedgelist()` but that update made it unnecessary. 

The `for` loop still makes things take a while with large networks, but it's not *that* long (10+ minutes isn't so bad in network analysis) and it's basically unavoidable with so many nodes. 

Using `microbenchmark` to test the speed benefit of dropping that line on one of the small test networks, there is a substantial (even if not all that noticeable) reduction in evaluation time.

```
Unit: milliseconds
                       expr     min       lq     mean   median      uq      max neval cld
  isnar::ssi(EFnet, "type") 35.8784 40.78495 61.63681 53.00295 67.0364 460.2893  1000   b
   ssi_tweak(EFnet, "type") 23.6358 26.46800 39.46567 34.33230 43.3550 317.4761  1000  a 
```

**Comment by mbojan** [comment]
Thanks a lot @jacob-long ! Good catch. This code is 6yrs old (wow...) and revising this is somewhere on my TODO list, but never made it to the top. I'll try to update that shortly.
