### ISSUE TITLE
devtools installation no such file or directory

### ISSUE THREAD

**Issue by jxu** [mbojan/isnar#9]
```
** inst
Warning in file.create(to[okay]) :
  cannot create file '[...]/Documents/R/win-library/3.6/00LOCK-isnar/00new/isnar/exdata/earnings.sav', reason 'No such file or directory'
Warning in file.create(to[okay]) :
  cannot create file '[...]/Documents/R/win-library/3.6/00LOCK-isnar/00new/isnar/exdata/gender_roles.txt', reason 'No such file or directory'
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : there is no package called 'isnar'
Calls: <Anonymous> -> findpack
Execution halted
```

(`[...]` is anonymizing placeholder)

**Comment by jxu** [comment]
I got it to work by installing into a temporary location, then copying the files over to R's site-library.

Install to temp location with something like
`with_libpaths(new='C:/Users/jxu/Rtemp', devtools::install_github("mbojan/isnar"))`

**Comment by mbojan** [comment]
It must be something with your setup. Folder permissions or antivirus perhaps... Glad you sorted it out.

**Comment by jxu** [comment]
I think it is due to the weird file system of the computer I was using which mounts Windows volumes on a Unix FS. Sometimes forward slashes and sometimes backwards slashes and the I guess the install script got confused.
